// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mqzecdfcrmyuwtcjjgme.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1xemVjZGZjcm15dXd0Y2pqZ21lIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI2OTY1MjcsImV4cCI6MjA2ODI3MjUyN30.mZZpPvCHr1sQKmBDinXW5rOjqIrZQqwjiBSpHSKf24E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});